# permissions for end users to view alertmanagerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertmanagerconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mimir-operator
    app.kubernetes.io/part-of: mimir-operator
    app.kubernetes.io/managed-by: kustomize
  name: alertmanagerconfig-viewer-role
rules:
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - alertmanagerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - alertmanagerconfigs/status
  verbs:
  - get
