# permissions for end users to edit mimirtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mimirtenant-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mimir-operator
    app.kubernetes.io/part-of: mimir-operator
    app.kubernetes.io/managed-by: kustomize
  name: mimirtenant-editor-role
rules:
- apiGroups:
  - mimir.grafana.com
  resources:
  - mimirtenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mimir.grafana.com
  resources:
  - mimirtenants/status
  verbs:
  - get
