---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - alertmanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - alertmanagerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - alertmanagerconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - mimirrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - mimirrules/finalizers
  verbs:
  - update
- apiGroups:
  - mimir.randgen.xyz
  resources:
  - mimirrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - get
  - list
  - watch
