apiVersion: mimir.randgen.xyz/v1alpha1
kind: MimirRules
metadata:
  labels:
    app.kubernetes.io/name: mimirrules
    app.kubernetes.io/instance: mimirrules-sample
    app.kubernetes.io/part-of: mimir-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mimir-operator
  name: mimirrules-sample
spec:
  id: "tenant1"
  url: "http://10.233.50.128"
  rules:
    selectors:
      - matchLabels:
          helm.sh/chart: loki-4.10.0