apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mimir-operator.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mimir.randgen.xyz
    resources:
      - mimirrules
      - mimiralertmanagerconfig
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mimir.randgen.xyz
    resources:
      - mimirrules/finalizers
      - mimiralertmanagerconfig/finalizers
    verbs:
      - update
  - apiGroups:
      - mimir.randgen.xyz
    resources:
      - mimirrules/status
      - mimiralertmanagerconfig/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mimir-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mimir-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "mimir-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
