apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir-operator.fullname" . }}
  labels:
    {{- include "mimir-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - port: {{ .Values.metricsService.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "mimir-operator.selectorLabels" . | nindent 4 }}
